elasticsearch_host: "http://10.0.0.25" #probably not yours
elasticsearch_port: 9200
elasticsearch_index: logstash-* #probably change this
elasticsearch_username: elastic #change this
elasticsearch_password: elastic #change this
OTX_Key_dm_lacia: '<put key here>'
whitelist_ips: ["8.8.8.8","8.8.4.4","0.0.0.0","1.1.1.1"] #also add CCU ips and probably honeypot ips